name: servicehub
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  provider: ^6.0.5
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  permission_handler: ^11.0.1
  intl: ^0.18.1
  confetti: ^0.7.0
  like_button: ^2.0.5
  grouped_list: ^5.1.2
  google_fonts: ^6.1.0
  go_router: ^12.1.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_ui_auth: ^1.10.0
  firebase_storage: ^11.5.1
  google_sign_in: ^6.1.6
  flutter_admin_scaffold: ^1.2.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo_serviceHub.png
    - assets/ServiceHub.png
    - assets/onboard.png
    - assets/undraw_search_app.svg
    - assets/undraw_businessman.svg
    - assets/undraw_progressive_app.svg
    - assets/undraw_world.svg
    - assets/undraw_select_option_re.svg
    - assets/undraw_fast_loading_re.svg
    - assets/undraw_mail_sent.svg
    - assets/aerial-view-businessman.png
    - assets/aerial-view-businessman-using-computer.png
    - assets/concept-marketing-medias-sociaux.png
    - assets/salle_serveur.png
    - assets/supplier.png
    - assets/undraw_home_screen.svg
    - assets/undraw_usability_testing.svg
    - assets/floeurs.png
    - assets/undraw_specs.svg
    - assets/digital_marketing.png
    - assets/video-production.png
    # - assets/femme_noire.png
    - assets/undraw_writer_re.svg
    - assets/undraw_color_palette.svg
    - assets/concept-cloud-ai.png
    - assets/undraw_different_love.svg
    - assets/realite-virtuelle.png
    - assets/undraw_done.svg
    - assets/alert.png
    - assets/avatar.png
    - assets/undraw_nakamoto.svg
    - assets/network-security.png
    - assets/network-config.png
    - assets/wireless-network.png
    - assets/undraw_programming.svg
    - assets/web-dev.png
    - assets/game-dev.png
    - assets/undraw_security_on.svg
    - assets/ethical-hacking.png
    - assets/cryptography.png
    - assets/rdbms.png
    - assets/nosql.png
    - assets/data-warehousing.png
    - assets/undraw_weather_notification.svg
    - assets/platform-as-a-service.png
    - assets/software-as-a-service.png
    - assets/undraw_firmware.svg
    - assets/deep-learning.png
    - assets/computer-vision.png
    - assets/undraw_smart_home.svg
    - assets/undraw_server_cluster.svg
    - assets/smart-home-tech.png
    - assets/industrial-iot.png
    - assets/undraw_data.svg
    - assets/predictive-analysis.png
    - assets/big-data.png
    - assets/business-intelligence.png
    - assets/user-experience.png
    - assets/user-interface.png
    - assets/undraw_add_to_cart.svg
    - assets/search-engine-opt.png
    - assets/social-media.png
    - assets/e-commerce-management.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
